### ISSUE TITLE
Custom model validation

### ISSUE THREAD

**Issue by pierregm** [frankie567/fastapi-users#117]
Hi,
I need to add some validators to my custom `User` model, that raise a `ValueError` if some set of constraints isn't respected. For example,
```python
class User(models.BaseUser):
    referrer_id: Optional[int] = None

    @pydantic.validator('referrer_id')
    def check_referrer(cls, v, values):
        if v is None and not values.get('is_superuser', False):
            raise ValueError('Referrer needed for standard user')
```
I expected any validation error to be caught when trying to access the `/users/register` route, so that the status code of the response would be 422, and the response body containing the standard validation error message. 

Instead, I get a 500.

Any pointer to what I'm missing will be deeply appreciated. And :+1: for this awesome work!

**Comment by frankie567** [comment]
Hi @pierregm!

Could you provide the error stack trace shown in the console running your server? Surely, it will give use good pointers to solve the problem 🙂

**Comment by pierregm** [comment]
Sure, here we go...
```python
INFO:     127.0.0.1:52969 - "POST /users/register HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File ".../lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File ".../lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File ".../lib/python3.7/site-packages/fastapi/applications.py", line 140, in __call__
    await super().__call__(scope, receive, send)
  File ".../lib/python3.7/site-packages/starlette/applications.py", line 134, in __call__
    await self.error_middleware(scope, receive, send)
  File ".../lib/python3.7/site-packages/starlette/middleware/errors.py", line 178, in __call__
    raise exc from None
  File ".../lib/python3.7/site-packages/starlette/middleware/errors.py", line 156, in __call__
    await self.app(scope, receive, _send)
  File ".../lib/python3.7/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "./bacon/main.py", line 27, in db_session_middleware
    response = await call_next(request)
  File ".../lib/python3.7/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File ".../lib/python3.7/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File ".../lib/python3.7/site-packages/starlette/exceptions.py", line 73, in __call__
    raise exc from None
  File ".../lib/python3.7/site-packages/starlette/exceptions.py", line 62, in __call__
    await self.app(scope, receive, sender)
  File ".../lib/python3.7/site-packages/starlette/routing.py", line 590, in __call__
    await route(scope, receive, send)
  File ".../lib/python3.7/site-packages/starlette/routing.py", line 208, in __call__
    await self.app(scope, receive, send)
  File ".../lib/python3.7/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File ".../lib/python3.7/site-packages/fastapi/routing.py", line 147, in app
    is_coroutine=is_coroutine,
  File ".../lib/python3.7/site-packages/fastapi/routing.py", line 78, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 1 validation error for UserBase
response -> referrer_id
  Referrer needed for standard user (type=value_error)
INFO:     127.0.0.1:52976 - "POST /users/login/jwt HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File ".../lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File ".../lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File ".../lib/python3.7/site-packages/fastapi/applications.py", line 140, in __call__
    await super().__call__(scope, receive, send)
  File ".../lib/python3.7/site-packages/starlette/applications.py", line 134, in __call__
    await self.error_middleware(scope, receive, send)
  File ".../lib/python3.7/site-packages/starlette/middleware/errors.py", line 178, in __call__
    raise exc from None
  File ".../lib/python3.7/site-packages/starlette/middleware/errors.py", line 156, in __call__
    await self.app(scope, receive, _send)
  File ".../lib/python3.7/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "./bacon/main.py", line 27, in db_session_middleware
    response = await call_next(request)
  File ".../lib/python3.7/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File ".../lib/python3.7/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File ".../lib/python3.7/site-packages/starlette/exceptions.py", line 73, in __call__
    raise exc from None
  File ".../lib/python3.7/site-packages/starlette/exceptions.py", line 62, in __call__
    await self.app(scope, receive, sender)
  File ".../lib/python3.7/site-packages/starlette/routing.py", line 590, in __call__
    await route(scope, receive, send)
  File ".../lib/python3.7/site-packages/starlette/routing.py", line 208, in __call__
    await self.app(scope, receive, send)
  File ".../lib/python3.7/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File ".../lib/python3.7/site-packages/fastapi/routing.py", line 133, in app
    raw_response = await dependant.call(**values)
  File ".../lib/python3.7/site-packages/fastapi_users/router/users.py", line 28, in login
    user = await user_db.authenticate(credentials)
  File ".../lib/python3.7/site-packages/fastapi_users/db/base.py", line 57, in authenticate
    user = await self.get_by_email(credentials.username)
  File ".../lib/python3.7/site-packages/fastapi_users/db/sqlalchemy.py", line 91, in get_by_email
    return await self._make_user(user) if user else None
  File ".../lib/python3.7/site-packages/fastapi_users/db/sqlalchemy.py", line 165, in _make_user
    return self.user_db_model(**user_dict)
  File ".../lib/python3.7/site-packages/pydantic/main.py", line 283, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for UserInDB
referrer_id
  Referrer needed for standard user (type=value_error)
```

**Comment by frankie567** [comment]
OK, I see where the problem comes from 🙂 As per [Pydantic documentation](https://pydantic-docs.helpmanual.io/usage/validators/#validate-always):

> For performance reasons, by default validators are not called for fields when a value is not supplied.

So your validator should look like:

```py
class User(models.BaseUser):
    referrer_id: Optional[int] = None

    @pydantic.validator('referrer_id', always=True)
    def check_referrer(cls, v, values):
        if v is None and not values.get('is_superuser', False):
            raise ValueError('Referrer needed for standard user')
```

For the record, here is what was happening:

* Since `referer_id` was not supplied in the request, the validator wasn't called.
* The controller then considers the payload is valid and proceeds to create the user in database. 
* However, at the end of the controller, we instantiate a new `User` object, and this time, `referer_id` has a value (the default, `None`), so the validator is called... And raises a `ValueError`.
* In that case, [FastAPI rightly considers that this is a server error](https://fastapi.tiangolo.com/tutorial/handling-errors/#requestvalidationerror-vs-validationerror), hence the error 500.

Cheers!

**Comment by pierregm** [comment]
Wow, duh... That was basically it (that, and the fact that I had added my validator to my custom `User` model but had forgotten to make my `UserUpdate` inherit from `User` when it is clearly specified in the docs...)
Thanks a million again for this very clear and educational explanation!
