### ISSUE TITLE
sqlalchemy.exc.CompileError: Unconsumed column names: items

### ISSUE THREAD

**Issue by fessacchiotto** [frankie567/fastapi-users#278]
Hi! I'm getting this error:

`sqlalchemy.exc.CompileError: Unconsumed column names: items`

when running a fastapi-users call to register a user, trying to integrate the fastapi sqlalchemy tutorial with the fastapi-users example. 

I think it could because of the specification of a one-to-many relationship between two models. 

The sqlalchemy models used are:

``` python

from sqlalchemy import Column, ForeignKey, Integer, String
from sqlalchemy.types import Numeric
from sqlalchemy.orm import relationship
from fastapi_users.db.sqlalchemy import GUID
from db import Base

class Item(Base):
    __tablename__ = "items"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String, nullable=True)
    description = Column(String, nullable=True)
    quantita = Column(Numeric(9, 3), nullable=True)
    importo = Column(Numeric(12, 4), nullable=True)
    user_id = Column(GUID(), ForeignKey("users.id", ondelete="CASCADE"))
    user = relationship("UserTable", back_populates="items")

```

``` python
from sqlalchemy import Column, String, DateTime
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
from fastapi_users.db import SQLAlchemyBaseUserTable
from db import Base

class UserTable(Base, SQLAlchemyBaseUserTable):
    __tablename__ = "users"

    first_name = Column(String(50), nullable=True)
    last_name = Column(String(50), nullable=True)
    created_date = Column(DateTime, default=func.now(), nullable=False)
    items = relationship("Item", back_populates="user", cascade="all, delete")
```

Any help will be much appreciated!

**Comment by fessacchiotto** [comment]
It is depending on a pydantic model used for User:

```python
class User(models.BaseUser):
    first_name: Optional[str] = None
    last_name: Optional[str] = None
    # items: List[Item] = []

    class Config:
        orm_mode = True

```
The ` items: List[Item] = [] ` line is triggering the error... why?

**Comment by fessacchiotto** [comment]
Posted to the fastapi github site (https://github.com/tiangolo/fastapi/issues/1808). Closing here. Thanks!

**Comment by fessacchiotto** [comment]
I'm still uncertain as what the root cause is. I'm going to reopen here too if I can get some help from this community too...

**Comment by fessacchiotto** [comment]
stacktrace of the error:

````
INFO:     127.0.0.1:52387 - "POST /auth/register HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/maurizio/projects/test-fastapi/env/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 386, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/maurizio/projects/test-fastapi/env/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/Users/maurizio/projects/test-fastapi/env/lib/python3.8/site-packages/fastapi/applications.py", line 181, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/maurizio/projects/test-fastapi/env/lib/python3.8/site-packages/starlette/applications.py", line 102, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/maurizio/projects/test-fastapi/env/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Users/maurizio/projects/test-fastapi/env/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/maurizio/projects/test-fastapi/env/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Users/maurizio/projects/test-fastapi/env/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/maurizio/projects/test-fastapi/env/lib/python3.8/site-packages/starlette/routing.py", line 550, in __call__
    await route.handle(scope, receive, send)
  File "/Users/maurizio/projects/test-fastapi/env/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/Users/maurizio/projects/test-fastapi/env/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/Users/maurizio/projects/test-fastapi/env/lib/python3.8/site-packages/fastapi/routing.py", line 196, in app
    raw_response = await run_endpoint_function(
  File "/Users/maurizio/projects/test-fastapi/env/lib/python3.8/site-packages/fastapi/routing.py", line 147, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/maurizio/projects/test-fastapi/env/lib/python3.8/site-packages/fastapi_users/router/register.py", line 38, in register
    created_user = await user_db.create(db_user)
  File "/Users/maurizio/projects/test-fastapi/env/lib/python3.8/site-packages/fastapi_users/db/sqlalchemy.py", line 153, in create
    await self.database.execute(query, user_dict)
  File "/Users/maurizio/projects/test-fastapi/env/lib/python3.8/site-packages/databases/core.py", line 161, in execute
    return await connection.execute(query, values)
  File "/Users/maurizio/projects/test-fastapi/env/lib/python3.8/site-packages/databases/core.py", line 262, in execute
    return await self._connection.execute(built_query)
  File "/Users/maurizio/projects/test-fastapi/env/lib/python3.8/site-packages/databases/backends/postgres.py", line 160, in execute
    query, args, result_columns = self._compile(query)
  File "/Users/maurizio/projects/test-fastapi/env/lib/python3.8/site-packages/databases/backends/postgres.py", line 184, in _compile
    compiled = query.compile(dialect=self._dialect)
  File "<string>", line 1, in <lambda>
  File "/Users/maurizio/projects/test-fastapi/env/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 476, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "/Users/maurizio/projects/test-fastapi/env/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 482, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/Users/maurizio/projects/test-fastapi/env/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 590, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/Users/maurizio/projects/test-fastapi/env/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 319, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/Users/maurizio/projects/test-fastapi/env/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 350, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/Users/maurizio/projects/test-fastapi/env/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 95, in _compiler_dispatch
    return meth(self, **kw)
  File "/Users/maurizio/projects/test-fastapi/env/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 2427, in visit_insert
    crud_params = crud._setup_crud_params(
  File "/Users/maurizio/projects/test-fastapi/env/lib/python3.8/site-packages/sqlalchemy/sql/crud.py", line 64, in _setup_crud_params
    return _get_crud_params(compiler, stmt, **kw)
  File "/Users/maurizio/projects/test-fastapi/env/lib/python3.8/site-packages/sqlalchemy/sql/crud.py", line 177, in _get_crud_params
    raise exc.CompileError(
sqlalchemy.exc.CompileError: Unconsumed column names: items

**Comment by fessacchiotto** [comment]
Closed the terminal window (on a Mac). Recreated from scratch the terminal and activated the virtual environment. The isseu disappeared. Closing for good. Sorry for this.
