### ISSUE TITLE
TypeError: __call__() takes 3 positional arguments but 4 were given (_update_user issue)

### ISSUE THREAD

**Issue by SelfhostedPro** [frankie567/fastapi-users#292]
This bit of code in users.py is what is causing the issue:
```
        if after_update:
            await run_handler(after_update, updated_user, update_dict, request)
```
Here is the full log:
```
INFO:     127.0.0.1:0 - "PATCH /api/users/me HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/user/dev/testing/yacht_fastapi/venv/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 390, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/user/dev/testing/yacht_fastapi/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/user/dev/testing/yacht_fastapi/venv/lib/python3.8/site-packages/fastapi/applications.py", line 181, in __call__
    await super().__call__(scope, receive, send)
  File "/home/user/dev/testing/yacht_fastapi/venv/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/user/dev/testing/yacht_fastapi/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/user/dev/testing/yacht_fastapi/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/user/dev/testing/yacht_fastapi/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/user/dev/testing/yacht_fastapi/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/user/dev/testing/yacht_fastapi/venv/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/user/dev/testing/yacht_fastapi/venv/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/user/dev/testing/yacht_fastapi/venv/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/user/dev/testing/yacht_fastapi/venv/lib/python3.8/site-packages/fastapi/routing.py", line 196, in app
    raw_response = await run_endpoint_function(
  File "/home/user/dev/testing/yacht_fastapi/venv/lib/python3.8/site-packages/fastapi/routing.py", line 147, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/user/dev/testing/yacht_fastapi/venv/lib/python3.8/site-packages/fastapi_users/router/users.py", line 67, in update_me
    updated_user = await _update_user(user, updated_user_data, request)
  File "/home/user/dev/testing/yacht_fastapi/venv/lib/python3.8/site-packages/fastapi_users/router/users.py", line 46, in _update_user
    await run_handler(after_update, updated_user, update_dict, request)
  File "/home/user/dev/testing/yacht_fastapi/venv/lib/python3.8/site-packages/fastapi_users/router/common.py", line 15, in run_handler
    handler(*args, **kwargs)
TypeError: __call__() takes 3 positional arguments but 4 were given
```
I am using cookie authentication if that changes anything. Commenting out the `if after_update` line fixes this issue for be so I suspect I may be doing something incorrect there.

**Comment by frankie567** [comment]
Could you provide your `on_after_update` function? It looks like an argument is missing.

**Comment by SelfhostedPro** [comment]
Ah, I never defined an on_after_update. I didn't know it was required.

-------- Original Message --------

**Comment by frankie567** [comment]
It's not required, unless you specify it in `get_users_router` method: https://frankie567.github.io/fastapi-users/configuration/routers/users/#after-update

**Comment by SelfhostedPro** [comment]
I don't have it specified anywhere afaik:
https://github.com/SelfhostedPro/Yacht/blob/c805270c1d6b6004881ca6e0e35bf9b4377ee1ac/backend/api/main.py#L32
^that is where my users router is specified

https://github.com/SelfhostedPro/Yacht/blob/vue/backend/api/auth/auth.py
^that is where I have configured FastAPI-users

**Comment by frankie567** [comment]
Here is the problem:

```py
    fastapi_users.get_users_router(cookie_authentication),
```

You pass `cookie_authentication`, which is wrong. You should pass either nothing, or an `on_after_update` function if you need one.

**Comment by SelfhostedPro** [comment]
Ahhh, perfect. I think I was confused by the official documentation as I was only using [this](https://frankie567.github.io/fastapi-users/configuration/routers/auth/) page to build the routes. I'll fix that. Thanks!
