### ISSUE TITLE
cannot import name 'FastAPIUsers' from 'fastapi_users'

### ISSUE THREAD

**Issue by lefnire** [frankie567/fastapi-users#303]
Following the SQLAlchemy tutorial. I'm indeed doing `from fastapi_users import FastAPIUsers`, but as you can see even without it `__init__.py` is trying same and can't reach it. Version 3.0.4.

```shell
$ pip install fastapi fastapi_users[sqlalchemy]
$ python
>>> import fastapi_users
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/fastapi_users/__init__.py", line 6, in <module>
    from fastapi_users.fastapi_users import FastAPIUsers  # noqa: F401
  File "/usr/local/lib/python3.7/site-packages/fastapi_users/fastapi_users.py", line 6, in <module>
    from fastapi_users.authentication import Authenticator, BaseAuthentication
  File "/usr/local/lib/python3.7/site-packages/fastapi_users/authentication/__init__.py", line 9, in <module>
    from fastapi_users.authentication.cookie import CookieAuthentication  # noqa: F401
  File "/usr/local/lib/python3.7/site-packages/fastapi_users/authentication/cookie.py", line 3, in <module>
    import jwt
  File "/app/app/jwt.py", line 2, in <module>
    from fastapi_users import FastAPIUsers
ImportError: cannot import name 'FastAPIUsers' from 'fastapi_users' (/usr/local/lib/python3.7/site-packages/fastapi_users/__init__.py)
```

**Comment by lefnire** [comment]
Hmm, new docker container with same deps no error. Maybe a fluke, I'll reopen if not
