### ISSUE TITLE
pydantic validation error for UserDB

### ISSUE THREAD

**Issue by sandeepdevagiri** [frankie567/fastapi-users#318]
I am using MongoDB backend for authentication and I am getting 500 Internal service error when trying to create a new user using register route.

Here is the code I am using

from fastapi import APIRouter
from fastapi_users import models, FastAPIUsers
from fastapi_users.db import MongoDBUserDatabase
from fastapi_users.authentication import JWTAuthentication
import motor.motor_asyncio

class User(models.BaseUser):
    pass

class UserCreate(models.BaseUserCreate):
    pass

class UserUpdate(models.BaseUserUpdate):
    pass

class UserDB(models.BaseUserDB):
    pass

DATABASE_URL = 'mongodb://xxx:xxx@xxx:27017/'
client = motor.motor_asyncio.AsyncIOMotorClient(DATABASE_URL, uuidRepresentation="standard")
db = client['auth']
collection = db['users']

SECRET = 'SECRET'

auth_backends = []

jwt_authentication = JWTAuthentication(secret=SECRET, lifetime_seconds=3600, tokenUrl='/auth/jwt/login')
auth_backends.append(jwt_authentication)

router = APIRouter()

user_db = MongoDBUserDatabase(UserDB, collection)

fastapiusers = FastAPIUsers(
    user_db,
    auth_backends,
    User,
    UserCreate,
    UserUpdate,
    UserDB,
)

router.include_router(fastapiusers.get_auth_router(jwt_authentication), prefix='/auth/jwt', tags=['auth'])
router.include_router(fastapiusers.get_register_router(), prefix='/auth', tags=['auth'])
router.include_router(fastapiusers.get_reset_password_router(SECRET), prefix='/auth', tags=['auth'])
router.include_router(fastapiusers.get_users_router(), prefix='/users', tags=['users'])

When I try to do create new user using /auth/register I am getting the below error

INFO:     127.0.0.1:49456 - "POST /auth/register HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/sandeepdevagiri/opt/anaconda3/envs/trading_api/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 390, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/sandeepdevagiri/opt/anaconda3/envs/trading_api/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/Users/sandeepdevagiri/opt/anaconda3/envs/trading_api/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/sandeepdevagiri/opt/anaconda3/envs/trading_api/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/sandeepdevagiri/opt/anaconda3/envs/trading_api/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Users/sandeepdevagiri/opt/anaconda3/envs/trading_api/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/sandeepdevagiri/opt/anaconda3/envs/trading_api/lib/python3.8/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/Users/sandeepdevagiri/opt/anaconda3/envs/trading_api/lib/python3.8/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/Users/sandeepdevagiri/opt/anaconda3/envs/trading_api/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Users/sandeepdevagiri/opt/anaconda3/envs/trading_api/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/sandeepdevagiri/opt/anaconda3/envs/trading_api/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/Users/sandeepdevagiri/opt/anaconda3/envs/trading_api/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/Users/sandeepdevagiri/opt/anaconda3/envs/trading_api/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/Users/sandeepdevagiri/opt/anaconda3/envs/trading_api/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
    raw_response = await run_endpoint_function(
  File "/Users/sandeepdevagiri/opt/anaconda3/envs/trading_api/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/sandeepdevagiri/opt/anaconda3/envs/trading_api/lib/python3.8/site-packages/fastapi_users/router/register.py", line 35, in register
    db_user = user_db_model(
  File "pydantic/main.py", line 346, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for UserDB
id
  field required (type=value_error.missing)

Indexes are getting created in Mongodb database

Name | Columns | Size | Attributes | Actions
_id_ | _id   ASC | 8 KB |   | DEL
case_insensitive_email_index | email   ASC | 8 KB | collation:  [object Object] | DEL
id_1 | id   ASC | 8 KB | unique:  true | DEL
email_1 | email   ASC | 8 KB | unique:  true | DEL

**Comment by frankie567** [comment]
Your `UserDB` class should inherit from the `User` class:

```
class UserDB(User, models.BaseUserDB):
    pass
```

**Comment by sandeepdevagiri** [comment]
Thanks.
