### ISSUE TITLE
typing_extensions not declared as a dependency

### ISSUE THREAD

**Issue by roywes** [frankie567/fastapi-users#401]
In [users.py](https://github.com/frankie567/fastapi-users/blob/253e7e0e8034902d2ebf90fda3d699005139b9fe/fastapi_users/user.py#L3), `Protocols` is imported from `typing_extensions`. However, this results in a `ModuleNotFoundError` as `typing_extensions` is not declared as a dependency,

Example traceback follows.

```
Traceback (most recent call last):
  ...
  File "/usr/local/lib/python3.9/site-packages/app/user_management.py", line 2, in <module>
    from fastapi_users import FastAPIUsers
  File "/usr/local/lib/python3.9/site-packages/fastapi_users/__init__.py", line 6, in <module>
    from fastapi_users.fastapi_users import FastAPIUsers  # noqa: F401
  File "/usr/local/lib/python3.9/site-packages/fastapi_users/fastapi_users.py", line 8, in <module>
    from fastapi_users.router import (
  File "/usr/local/lib/python3.9/site-packages/fastapi_users/router/__init__.py", line 3, in <module>
    from fastapi_users.router.register import get_register_router  # noqa: F401
  File "/usr/local/lib/python3.9/site-packages/fastapi_users/router/register.py", line 7, in <module>
    from fastapi_users.user import CreateUserProtocol, UserAlreadyExists
  File "/usr/local/lib/python3.9/site-packages/fastapi_users/user.py", line 3, in <module>
    from typing_extensions import Protocol
ModuleNotFoundError: No module named 'typing_extensions'
```

**Comment by frankie567** [comment]
I just thought about that when reviewing your PR! Will fix this ASAP.

**Comment by frankie567** [comment]
@all-contributors add @roywes for bug, code
