### ISSUE TITLE
Bug: ASGI exception when calling register endpoint

### ISSUE THREAD

**Issue by newageoflight** [frankie567/fastapi-users#419]
**Platform:** Windows 10, Python 3.8.5, latest versions of FastAPI and FastAPI Users. Identical behaviour when tested on Ubuntu 20.04 LTS via WSL.

**Expected behaviour:** registration occurs as documented in the API.

**Actual behaviour:** 500 Internal Server Error as follows:
```
INFO:     127.0.0.1:0 - "POST /api/v1/auth/register HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\camin\AppData\Local\Programs\Python\Python38\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 388, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\camin\AppData\Local\Programs\Python\Python38\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\camin\AppData\Local\Programs\Python\Python38\lib\site-packages\fastapi\applications.py", line 190, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\camin\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\camin\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "C:\Users\camin\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\camin\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "C:\Users\camin\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\camin\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\camin\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "C:\Users\camin\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\routing.py", line 41, in app
    response = await func(request)
  File "C:\Users\camin\AppData\Local\Programs\Python\Python38\lib\site-packages\fastapi\routing.py", line 188, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\camin\AppData\Local\Programs\Python\Python38\lib\site-packages\fastapi\routing.py", line 135, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\camin\AppData\Local\Programs\Python\Python38\lib\site-packages\fastapi_users\router\register.py", line 24, in register
    created_user = await create_user(user, safe=True)
  File "C:\Users\camin\AppData\Local\Programs\Python\Python38\lib\site-packages\fastapi_users\user.py", line 31, in create_user
    existing_user = await user_db.get_by_email(user.email)
  File "C:\Users\camin\AppData\Local\Programs\Python\Python38\lib\site-packages\fastapi_users\db\mongodb.py", line 49, in get_by_email
    user = await self.collection.find_one(
RuntimeError: Task <Task pending name='Task-5' coro=<RequestResponseCycle.run_asgi() running at C:\Users\camin\AppData\Local\Programs\Python\Python38\lib\site-packages\uvicorn\protocols\http\h11_impl.py:388> cb=[set.discard()]> got Future <Future pending cb=[_chain_future.<locals>._call_check_cancel() at 
C:\Users\camin\AppData\Local\Programs\Python\Python38\lib\asyncio\futures.py:360]> attached to a different loop
```

**Additional information:** Using MongoDB/Motor backend

**Comment by frankie567** [comment]
This is something I come across in my own projects  from time to time ; it happens when several async loops are created and used. Could you provide your motor and fastapi-users configuration?
