### ISSUE TITLE
Getting error "Task <...> got Future <...> attached to a different loop"

### ISSUE THREAD

**Issue by scherzocrk** [frankie567/fastapi-users#679]
## Configuration
 - Python version : 3.9.6
 - FastAPI version : 0.68.0
 - FastAPI Users version : 6.1.1

## Steps to reproduce

The following sample reproduces the above issue.

[sample_v2.zip](https://github.com/frankie567/fastapi-users/files/6949742/sample_v2.zip)

## Describe the bug

I've found an interesting issue, not really sure if it's related to fastapi_users but I think so. 
For development purposes, I have two options to launch my app:

1. Running the command "uvicorn main:app --reload"
2. Putting the python code below in my main.py and calling "python main.py"

```
import uvicorn
if __name__ == "__main__":
    uvicorn.run(
        "main:app", host="127.0.0.1", port=8000, reload=settings.DEBUG_MODE
    )
```

Option 2 is good for me because it allows me to debug the backend inside vscode.

If I run the full example code available in the docs https://frankie567.github.io/fastapi-users/configuration/full-example.html everything is fine, using option 1 or 2.

Now, if I put fastapi_users part of the code in a different file and import this code in the main fastapi file like this `app.include_router(auth.router)`, Option 1 runs fine, but Option 2 gives me the following error during login

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "c:\Users\scherzo\Downloads\vida-swipe-v2\backend\.venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "c:\Users\scherzo\Downloads\vida-swipe-v2\backend\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "c:\Users\scherzo\Downloads\vida-swipe-v2\backend\.venv\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "c:\Users\scherzo\Downloads\vida-swipe-v2\backend\.venv\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "c:\Users\scherzo\Downloads\vida-swipe-v2\backend\.venv\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "c:\Users\scherzo\Downloads\vida-swipe-v2\backend\.venv\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "c:\Users\scherzo\Downloads\vida-swipe-v2\backend\.venv\lib\site-packages\starlette\middleware\cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "c:\Users\scherzo\Downloads\vida-swipe-v2\backend\.venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "c:\Users\scherzo\Downloads\vida-swipe-v2\backend\.venv\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "c:\Users\scherzo\Downloads\vida-swipe-v2\backend\.venv\lib\site-packages\starlette\routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "c:\Users\scherzo\Downloads\vida-swipe-v2\backend\.venv\lib\site-packages\starlette\routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "c:\Users\scherzo\Downloads\vida-swipe-v2\backend\.venv\lib\site-packages\starlette\routing.py", line 52, in app
    response = await func(request)
  File "c:\Users\scherzo\Downloads\vida-swipe-v2\backend\.venv\lib\site-packages\fastapi\routing.py", line 219, in app
    raw_response = await run_endpoint_function(
  File "c:\Users\scherzo\Downloads\vida-swipe-v2\backend\.venv\lib\site-packages\fastapi\routing.py", line 152, in run_endpoint_function
    return await dependant.call(**values)
  File "c:\Users\scherzo\Downloads\vida-swipe-v2\backend\.venv\lib\site-packages\fastapi_users\router\auth.py", line 26, in login
    user = await user_db.authenticate(credentials)
  File "c:\Users\scherzo\Downloads\vida-swipe-v2\backend\.venv\lib\site-packages\fastapi_users\db\base.py", line 54, in authenticate
    user = await self.get_by_email(credentials.username)
  File "c:\Users\scherzo\Downloads\vida-swipe-v2\backend\.venv\lib\site-packages\fastapi_users\db\mongodb.py", line 49, in get_by_email
    user = await self.collection.find_one(
RuntimeError: Task <Task pending name='Task-4' coro=<RequestResponseCycle.run_asgi() running at c:\Users\scherzo\Downloads\vida-swipe-v2\backend\.venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py:396> cb=[set.discard()]> got Future <Future pending cb=[_chain_future.<locals>._call_check_cancel() at C:\Program Files\Python39\lib\asyncio\futures.py:384]> attached to a different loop
```

**Comment by scherzocrk** [comment]
The following sample reproduces the above issue.

[sample_v2.zip](https://github.com/frankie567/fastapi-users/files/6949742/sample_v2.zip)

**Comment by frankie567** [comment]
Hi there!

Sorry for the delayed response!

It actually happens because Uvicorn tends to instantiate its own event loop. I gave explanations about this in the following discussion: https://github.com/frankie567/fastapi-users/discussions/663#discussioncomment-1025558

In a nutshell, put your FastAPI app instantiation and the Uvicorn invokation in two separate files.
